# Generated by Django 3.0.8 on 2020-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFlowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
